let TMDB_BASE = 'https://image.tmdb.org/t/p'

// try to load generated config module if present; fall back to default base
(async () => {
  try {
    // tmdbConfig.js is generated by scripts/fetchTmdbConfig.mjs
    const cfg = await import('../data/tmdbConfig.js')
    if (cfg && cfg.TMDB_IMAGE_BASE) {
      TMDB_BASE = cfg.TMDB_IMAGE_BASE
    }
  } catch (err) {
    // ignore — use fallback
  }
})()

/**
 * @param {string} filePath - e.g. "/abc123.jpg"
 * @param {'w300' | 'w500' | 'w780' | 'w1280' | 'original'} [size]
 */
export function tmdbImage(filePath, size = 'w780') {
  if (!filePath) return ''
  // ensure no double slash when base already contains trailing slash
  const base = TMDB_BASE.replace(/\/+$/, '')
  return `${base}/${size}${filePath}`
}

/**
 * @param {string[]} paths
 * @param {'w300' | 'w500' | 'w780' | 'w1280' | 'original'} [size]
 */
export function tmdbImages(paths, size = 'w780') {
  return paths.map((p) => tmdbImage(p, size))
}

/**
 * Scene still — full URL (Guardian, etc.) or TMDB file path.
 * @param {string} pathOrUrl
 * @param {'w300' | 'w500' | 'w780' | 'w1280' | 'original'} [size]
 */
export function resolveSceneImage(pathOrUrl, size = 'w1280') {
  if (!pathOrUrl) return ''
  if (pathOrUrl.startsWith('http://') || pathOrUrl.startsWith('https://')) {
    return pathOrUrl
  }
  return tmdbImage(pathOrUrl, size)
}
